### ISSUE TITLE
Highlight cursor setting makes Ctrl remove focus from input

### ISSUE THREAD

**Issue by m93a** [elementary/switchboard-plug-mouse-touchpad#96] opened 2019-09-29 22:47 UTC
## Describe the bug
When the option "Highlight cursor: Pressing Ctrl will highlight the position of the cursor" (sorry if the translation is not literal) is activated, pressing Ctrl causes text input fields to lose focus until the key is let up again. This causes some aplications that change cursor position based on focus to behave badly. For example, the web application Messenger moves the cursor to the beginning of input on every focus event. This causes combinations like Ctrl+Backspace and Ctrl+Arrow completely useless.

### To Reproduce
1. Go to *Mouse and touchpad* in Switchboard
2. Enable the *Highlight cursor* option
3. Open this website in a browser: https://jsfiddle.net/r6co502L/1/
4. Click on the textarea
5. Write something
6. Press Ctrl+Left Arrow

### Expected behavior
The textarea shouldn't lose focus.

### Acutal behavior
The textarea loses focus when Ctrl is down and regains it when Ctrl is up.

### Screenshots or screen recordings

![obrazek](https://user-images.githubusercontent.com/1671665/65840645-bf9efa80-e31b-11e9-8313-c3c3cc22e8b8.png)

## Platform Information
![obrazek](https://user-images.githubusercontent.com/1671665/65840531-a47fbb00-e31a-11e9-90bf-1d0c230a8bc3.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by bumper314** [comment] 2019-10-15 10:59
Nice [jsfiddle](https://jsfiddle.net/r6co502L/1/) testcase.  In my testing…

1. With "Reveal pointer" enabled, pressing Ctrl does blur (lose focus) of the textfield, but I was able to press left arrow or Backspace and everything worked as expected.  If it doesn't work for @m93a, then perhaps there's an interaction with the Language/Input Method selection.  I'm using English, what are you using?

2. Pressing the Meta key also causes the textfield to blur, even with Keyboard > Layout > "⌘ key behavior" => Disabled.  I didn't notice any adverse effects, I just thought it was worth mentioning.  Conceivably, any action that causes a field to lose focus unexpectedly could have unforeseen consequences.

**Comment by m93a** [comment] 2019-10-16 07:15
1. Can confirm that the textfield regains focus as soon as I press an arrow, even with Czech keyboard layout. But this is still enough to mess up some (arguably badly written but nonetheless popular) applications, for example Facebook's [Messenger](https://messenger.com).
2. Can confirm this as well. I opened [an issue](https://github.com/elementary/switchboard-plug-keyboard/issues/253) for it in the corresponding repo.

**Comment by danrabbit** [comment] 2020-01-10 16:48
Closing as a duplicate of #81

**Closed by danrabbit** 2020-01-10 16:48 UTC
