### ISSUE TITLE
Elementary 6.0: Bluetooth mouse natural scroll

### ISSUE THREAD

**Issue by Ppamungkas** [elementary/switchboard-plug-mouse-touchpad#156] opened 2020-11-24 06:39 UTC
Bluetooth mouse natural scroll is turned off when booting and while working with the computer.

## What Happened
On every boot the natural scroll need to be switch off and on again to have the natural scroll working.
While working, the natural scroll suddenly changed, the config in system settings is still on, after turn off and on the natural scroll is back.

## Expected Behavior
Natural scroll should be not off by itself.

## Steps to Reproduce

1. Connect a bluetooth mouse and use natural scroll
2. Reboot Computer.
3. Natural scroll is loss.

## Platform Information
- Elementary 6.0 Next
- Laptop is Asus UM425I
- Mouse Logitech Pebble M350

**Comment by Ppamungkas** [comment] 2020-11-27 03:41
This link solve my problem.

Maybe hook the setting to the options?

https://askubuntu.com/questions/1282097/20-04-natural-scrolling-not-persisting-between-sessions/1283546#1283546

**Comment by danrabbit** [comment] 2020-11-27 03:50
From the discussion on StackExchange it sounds like this is an upstream issue either in GNOME Settings Daemon or in Libinput. Either way the fact that it can be reproduced in GNOME Settings means it's not an issue with our code here

Closing the issue as "Out of Scope" since it can't be resolved in this code case

Please pursue this issue upstream in GNOME Settings Daemon on GitLab

**Closed by danrabbit** 2020-11-27 03:50 UTC
