### ISSUE TITLE
Two-finger scrolling is not working

### ISSUE THREAD

**Issue by NewtonGauss** [elementary/switchboard-plug-mouse-touchpad#111] opened 2019-11-25 13:27 UTC
Hello, I've installed elementary OS a couple weeks ago and I'm pretty new in Linux. I used to have windows 10 in my laptop and the two-finger scrolling feature worked fine, but since I have elementary OS, that feature is not working at all. I've checked on google and found nothing that helped me. I've also turned on two-finger scrolling in the system configuration and nothing happened. My laptop is a Compaq Presario 21N2F5AR.
![Captura de pantalla de 2019-11-25 10-20-46](https://user-images.githubusercontent.com/58175814/69543900-4e6f7280-0f6d-11ea-8f1f-313055d44cba.png)

**Comment by danrabbit** [comment] 2021-04-10 19:43
This sounds like a possible driver issue with Linux 4.15. These days elementary OS 5.x uses Linux 5.4 and elementary OS 6 will use 5.8.

If the issue can be reproduced with the 5.8 kernel in elementary OS 6, the issue should be reported upstream to Ubuntu in launchpad.

Closing as "out of scope" since drivers are the responsibility of the Ubuntu kernel and the issue cannot be resolved in the scope of mouse and touchpad settings

**Closed by danrabbit** 2021-04-10 19:43 UTC
