### ISSUE TITLE
Can not disable middle click paste

### ISSUE THREAD

**Issue by IamLizu** [elementary/switchboard-plug-mouse-touchpad#69] opened 2019-01-07 22:00 UTC
System is updated. I see that even if I disable **middle click paste** from the system settings, its stays enabled.

**Comment by peteruithoven** [comment] 2019-01-07 22:04
In all apps? Even the native (gtk3) ones?
Relevant: https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/46#issuecomment-436626376

**Comment by IamLizu** [comment] 2019-01-07 22:21
Its kinda weird, now its not working at all even if function is enabled. I see some other users also complaining about this on elementary OS Stack Exchange site.

**Comment by peteruithoven** [comment] 2019-01-07 22:54
I now see that a fix:
https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/46
Was merged after the latest release:
https://github.com/elementary/switchboard-plug-mouse-touchpad/releases

Could you try it with the `master` version? As in you clone, build and install the latest version?
These instructions should help:
https://github.com/elementary/switchboard-plug-mouse-touchpad#building-and-installation

**Comment by sprite-1** [comment] 2019-01-23 13:17
I have the original issue as well. Even if the setting is set to disable, it's still enabled in the system.

It works without problems on native GTK apps such as Code and AppCenter but not on non-GTK like Firefox or Sublime Text 3

**Comment by arshubham** [comment] 2019-09-22 07:42
@sprite-1 It is upto the 3rd party toolkits/apps to respect the middle click setting. By default only gtk apps are ensured to work. Vscode provides `"editor.selectionClipboard": false` setting to disable middle click paste.

@IamLizu Are you still experiencing this issue?

**Comment by sprite-1** [comment] 2019-09-22 09:42
@arshubham then there should be a disclaimer there when toggling it because I can see the average user just seeing this as a "broken feature"

**Comment by arshubham** [comment] 2019-09-22 10:05
@sprite-1 Yeah will look into clarifying the help text more.

**Comment by danrabbit** [comment] 2020-01-10 16:37
It sounds like this is working as intended but some 3rd party apps are overriding or providing their own behaviors.

We already disclaimer in AppCenter and Sideload that uncurated apps haven't been tested for integration and may exhibit unexpected behavior, so I don't think additional text here really makes sense. That could be said for many many settings and would just clutter things up.

I'm going to close this as "Out of Scope" since it sound like the actual issue is in some other app and an issue report should be filed against that app

**Closed by danrabbit** 2020-01-10 16:37 UTC
