### ISSUE TITLE
[suggestion] Add function to enable double click behaviour for "files" in system settings

### ISSUE THREAD

**Issue by tuxiano** [elementary/switchboard-plug-mouse-touchpad#78] opened 2019-03-12 20:40 UTC
Hi,

maybe I'm too old, but I can't get used to the single click behaviour in the file manager and I'm quite sure, that I'm not alone with this problem (see elementaryos.stackexchange.com). 

I really would be grateful, if you could provide people like me an option in the system settings to choose between single click or double click behaviour.

Thank you

**Comment by jeremypw** [comment] 2019-03-13 11:45
Although I have some sympathy with exposing this setting, I think the UX team would prefer to work on making the single-click mode more intuitive and easier to use so any suggestions along those lines would be of interest. 

As you may know, Files does, for now, continue to support double-click mode and this can be enabled by typing into a terminal:
```
gsettings set io.elementary.files.preferences single-click false
```

Or use dconf-editor to change this and other app settings.

**Comment by jeremypw** [comment] 2019-03-13 12:09
The fix for getting IDLE to list in "All other applications" is to change the desktop file Exec line to:
```
Exec=/usr/bin/idle-python3.6 %U
```

Clearly, to open a file with an application, the application must be capable of receiving the file location as a parameter.  The desktop file in the IDLE package indicates that the application does *not* accept a file commandline parameter so the dialog does not list it.

Therefore I am not convinced that this is a Files bug.

It maybe that in Fedora a correct package is supplied.

**Comment by tuxiano** [comment] 2019-03-13 19:15
Thank you for your feedback and the trick to disabling single-click via terminal. 

In general, I found single-click "dangerous", because you can easily execute a non-reviewed shell-script or other executable. If you ask me, single-click should be an option and double-click the default.

**Comment by jeremypw** [comment] 2019-03-13 19:29
There are some some checks to prevent execution of files that are not expected to be executable or that have not been deliberately marked executable but I doubt they are foolproof.  I would like to increase the target area for selection and decrease it for activation but whether that would get past the UX team is unknown.

**Comment by jeremypw** [comment] 2019-03-13 19:33
Actually, I think just clicking on an executable does not execute it.  You can only run an executable using the context menu.

**Comment by tuxiano** [comment] 2019-03-13 19:45
If I click on a sh-file it gets executed (at least on my system). A white window pops, which instantly disappears.

**Comment by jeremypw** [comment] 2019-03-13 20:01
If you right click on the file, what is the first entry in the context menu?  When I activate an (executable) .sh file (permissions 775) it opens with a text editor.

**Comment by jeremypw** [comment] 2019-03-13 20:07
This fairly old merge should have introduced "edit by default" behaviour - https://github.com/elementary/files/pull/223 - maybe there has been a regression?

**Comment by tuxiano** [comment] 2019-03-13 20:21
No regression, I just noticed that it opens the sh file in emacs. Emacs closes directly because of this issue:

https://elementaryos.stackexchange.com/questions/797/how-to-get-gnu-emacs-work-on-elementary-os/4573#4573

So, its okay. Thank you.

**Comment by jeremypw** [comment] 2019-03-14 11:56
That's a relief - thanks.

**Comment by m93a** [comment] 2019-09-30 13:57
I also prefer the *"double-click to open and single-click to select"* behavior and while the terminal command to change it is very simple, I feel like it goes against the ideals of elementary OS a little. Having all the important settings in one place and not having to google the solutions is one of the things that makes eOS so delightful to use for me.

**Comment by jeremypw** [comment] 2019-10-22 17:33
See also https://github.com/elementary/files/pull/1067 as an alternative solution.  I do not think adding a setting that affects only one app to a global settings plug would be accepted.  There has recently been a softening of resistance against a setting menu in Files.

**Comment by danrabbit** [comment] 2021-04-10 18:38
Closing since we've changed the click method in Files to a mixed mode: single click navigate, double click launch

**Closed by danrabbit** 2021-04-10 18:38 UTC
Labels: Needs Design, Priority: Wishlist
