### ISSUE TITLE
Pointer reveal doesn't work

### ISSUE THREAD

**Issue by eliocamp** [elementary/switchboard-plug-mouse-touchpad#149] opened 2020-06-10 23:59 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

After activating pointer reveal, pressing control doesn't do anything. 

### To Reproduce
1. Go to Settings -> Mouse & Touchpad -> Pointing
2. Activate Reveal Pointer.
3. Press control

### Expected behavior

The position of the pointer should be highlighted

### Screenshots or screen recordings

![Peek 2020-06-10 20-38](https://user-images.githubusercontent.com/8617595/84329214-85e4eb80-ab5a-11ea-88e8-9573bf775693.gif)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment] 2021-04-10 18:28
For elementary OS 6, pointer reveal is now handled by our window manager Gala. This issue is likely resolved and I cannot reproduce it.

Closing as "incomplete". Please reopen if you can still reproduce the issue in elementary OS 6

**Closed by danrabbit** 2021-04-10 18:28 UTC
