### ISSUE TITLE
touchpad scrolling

### ISSUE THREAD

**Issue by rahayon** [elementary/switchboard-plug-mouse-touchpad#103] opened 2019-10-17 13:11 UTC
Touchpad Scrolling is not working with edge

**Comment by danrabbit** [comment] 2021-04-10 18:40
I'm unable to reproduce this issue on elementary OS 6. Closing as "incomplete". Please reopen the issue with more information if you're able to reproduce on elementary OS 6

**Closed by danrabbit** 2021-04-10 18:40 UTC
Labels: Status: Incomplete
