### ISSUE TITLE
Configurable trackpad gestures

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/switchboard-plug-mouse-touchpad#145] opened 2020-05-07 00:52 UTC
Currently, very few linux distros have this out of the box. This is very essential IMHO for speed and productivity. There are a couple of tools that I often resort to and it would be great if one of them (whatever the team decides is the best) could be added natively to EOS so people don't have to go fiddling around with installing them after the fact. The process is far from user friendly. 
The options I normally resort to are:
1. Mtrack
2. Fusuma
3. Xdtools/libinput gestures(using currently)

Thank you

**Comment by danrabbit** [comment] 2020-05-07 00:58
Closing as a duplicate of #16

**Closed by danrabbit** 2020-05-07 00:58 UTC
