### ISSUE TITLE
Enabling Reveal pointer option interferes with normal use of CTRL key

### ISSUE THREAD

**Issue by ClarkWalker** [elementary/switchboard-plug-mouse-touchpad#81] opened 2019-06-20 23:28 UTC
Bug description: Reveal pointer option (System Settings -> Mouse & Touchpad, General(tab): Reveal pointer) interferes with normal use of the CTRL key.
Example: text is deselected when trying to copy using `ctrl + c`. Other shortcuts using CTRL break as well.

**Comment by arshubham** [comment] 2019-09-18 18:35
@ClarkWalker Can you give more information on which application you are facing this issue? I am unable to reproduce it on my system on Gtk and electron apps.

**Comment by feoh** [comment] 2020-05-14 18:03
> @ClarkWalker Can you give more information on which application you are facing this issue? I am unable to reproduce it on my system on Gtk and electron apps.

I'm not @ClarkWalker but I can attest that I've experienced this issue in MAME and also the Amazon Workspaces client in windowed mode.

**Comment by cassidyjames** [comment] 2020-05-14 18:04
Ah I found that #26 was actually filed first. I'm gonna consolidate on that issue since it's the earliest reported version, and I'll re-open it since people have said this issue isn't present on Ubuntu or with GNOME Shell—so it might be caused by something we're doing.

Duplicate of #26

**Closed by cassidyjames** 2020-05-14 18:04 UTC
Labels: Status: Incomplete
